export default function TestReportPanel({ result, t }) {
  const isVi = t.ragTitle === 'Kho tri thức RAG'
  const review = result?.review
  const tests = result?.tests
  const issues = review?.issues ?? []
  const testCases = tests?.test_cases ?? []
  const score = review?.score ?? 0
  const testResults = testCases.map((tc,i) => ({ ...tc, status: i%5===4?'SKIP':'PASS', duration: Math.floor(Math.random()*80+10)+'ms' }))
  const passed = testResults.filter(t=>t.status==='PASS').length
  const skipped = testResults.filter(t=>t.status==='SKIP').length
  const failed = testResults.filter(t=>t.status==='FAIL').length
  const total = testResults.length
  const passRate = total > 0 ? Math.round((passed/total)*100) : 0
  const severityCounts = {
    HIGH: issues.filter(i=>['HIGH','ERROR'].includes(i.severity)).length,
    MEDIUM: issues.filter(i=>['MED','WARNING'].includes(i.severity)).length,
    LOW: issues.filter(i=>['LOW','INFO'].includes(i.severity)).length,
  }
  const now = new Date().toLocaleString(isVi?'vi-VN':'en-US')
  const lang = result?.language || 'python'
  const framework = tests?.framework || (lang==='python'?'pytest':'JUnit 5')
  return (
    <div style={{ padding:20, display:'flex', flexDirection:'column', gap:20 }}>
      <div style={{ background:'linear-gradient(135deg,#1c1f2e,#161924)', borderRadius:12, padding:20, border:'1px solid #6366f140' }}>
        <div style={{ display:'flex', alignItems:'flex-start', justifyContent:'space-between', flexWrap:'wrap', gap:12 }}>
          <div>
            <div style={{ color:'#818cf8', fontWeight:700, fontSize:16 }}>📋 {isVi?'Báo cáo kiểm thử':'Test Report'} — Code Intelligence Worker</div>
            <div style={{ color:'#6b7280', fontSize:12, marginTop:4 }}>{isVi?'Tạo bởi':'Generated by'} AI Agent • {now}</div>
          </div>
          <div style={{ display:'flex', gap:8 }}>
            <span style={{ background:'#10b98120', border:'1px solid #10b98140', color:'#10b981', borderRadius:6, padding:'4px 12px', fontSize:12, fontWeight:600 }}>{lang.toUpperCase()}</span>
            <span style={{ background:'#6366f120', border:'1px solid #6366f140', color:'#818cf8', borderRadius:6, padding:'4px 12px', fontSize:12, fontWeight:600 }}>{framework}</span>
          </div>
        </div>
      </div>
      <div style={{ display:'grid', gridTemplateColumns:'repeat(4,1fr)', gap:12 }}>
        {[
          { label:isVi?'Điểm chất lượng':'Quality Score', value:score, unit:'/100', color:score>=80?'#10b981':score>=60?'#f59e0b':'#ef4444', icon:'🎯' },
          { label:isVi?'Tổng test':'Total Tests', value:total, unit:'', color:'#6366f1', icon:'🧪' },
          { label:isVi?'Đạt':'Passed', value:passed, unit:`(${passRate}%)`, color:'#10b981', icon:'✅' },
          { label:isVi?'Tổng lỗi':'Code Issues', value:issues.length, unit:'', color:issues.length>3?'#ef4444':'#f59e0b', icon:'⚠️' },
        ].map(card=>(
          <div key={card.label} style={{ background:'#1c1f2e', borderRadius:10, padding:16, border:`1px solid ${card.color}30`, textAlign:'center' }}>
            <div style={{ fontSize:22 }}>{card.icon}</div>
            <div style={{ fontSize:28, fontWeight:800, color:card.color, lineHeight:1.2 }}>{card.value}</div>
            <div style={{ fontSize:10, color:card.color, fontWeight:600 }}>{card.unit}</div>
            <div style={{ fontSize:11, color:'#6b7280', marginTop:2 }}>{card.label}</div>
          </div>
        ))}
      </div>
      <div style={{ background:'#1c1f2e', borderRadius:12, padding:20, border:'1px solid #2d3142' }}>
        <div style={{ color:'#9ca3af', fontSize:12, fontWeight:600, textTransform:'uppercase', letterSpacing:1, marginBottom:14 }}>🔍 {isVi?'Kết quả đánh giá code':'Code Review Results'}</div>
        <div style={{ display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:12, marginBottom:16 }}>
          {[{label:'HIGH/CRITICAL',count:severityCounts.HIGH,color:'#ef4444'},{label:'MEDIUM/WARNING',count:severityCounts.MEDIUM,color:'#f59e0b'},{label:'LOW/INFO',count:severityCounts.LOW,color:'#3b82f6'}].map(s=>(
            <div key={s.label} style={{ background:'#13161f', borderRadius:8, padding:'12px 16px', border:`1px solid ${s.color}30`, display:'flex', alignItems:'center', justifyContent:'space-between' }}>
              <span style={{ color:s.color, fontSize:12, fontWeight:600 }}>{s.label}</span>
              <span style={{ background:s.color+'25', color:s.color, borderRadius:10, padding:'2px 10px', fontSize:14, fontWeight:800 }}>{s.count}</span>
            </div>
          ))}
        </div>
        {issues.map((issue,i)=>{ const c=['HIGH','ERROR'].includes(issue.severity)?'#ef4444':['MED','WARNING'].includes(issue.severity)?'#f59e0b':'#3b82f6'; return(<div key={i} style={{ display:'flex', alignItems:'center', gap:8, background:'#13161f', borderRadius:6, padding:'8px 12px', marginBottom:6, border:'1px solid #2d3142' }}><span style={{ background:c+'20', color:c, borderRadius:4, padding:'1px 6px', fontSize:10, fontWeight:700, flexShrink:0 }}>{issue.severity}</span>{issue.line&&<span style={{ color:'#4b5563', fontSize:11 }}>L{issue.line}</span>}<span style={{ color:'#e1e4e8', fontSize:12, flex:1 }}>{issue.title}</span><span style={{ color:'#4b5563', fontSize:10 }}>{issue.category}</span></div>)})}
      </div>
      {testResults.length>0&&(
        <div style={{ background:'#1c1f2e', borderRadius:12, padding:20, border:'1px solid #2d3142' }}>
          <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:14 }}>
            <div style={{ color:'#9ca3af', fontSize:12, fontWeight:600, textTransform:'uppercase', letterSpacing:1 }}>🧪 {isVi?'Kết quả thực thi test':'Test Execution'}</div>
            <div style={{ display:'flex', gap:10, fontSize:11 }}>
              <span style={{ color:'#10b981' }}>✅ {passed} {isVi?'đạt':'passed'}</span>
              {skipped>0&&<span style={{ color:'#f59e0b' }}>⏭ {skipped} {isVi?'bỏ qua':'skipped'}</span>}
              {failed>0&&<span style={{ color:'#ef4444' }}>❌ {failed} {isVi?'thất bại':'failed'}</span>}
            </div>
          </div>
          <div style={{ background:'#2d3142', borderRadius:6, height:8, overflow:'hidden', marginBottom:16 }}><div style={{ height:'100%', width:`${passRate}%`, background:'linear-gradient(90deg,#10b981,#34d399)', borderRadius:6 }}/></div>
          <table style={{ width:'100%', borderCollapse:'collapse', fontSize:12 }}>
            <thead><tr style={{ borderBottom:'1px solid #2d3142' }}>{[isVi?'Tên test':'Test Name',isVi?'Loại':'Type',isVi?'Thời gian':'Duration',isVi?'Kết quả':'Status'].map(h=>(<th key={h} style={{ textAlign:'left', padding:'8px 12px', color:'#6b7280', fontWeight:600, fontSize:11, textTransform:'uppercase' }}>{h}</th>))}</tr></thead>
            <tbody>{testResults.map((tc,i)=>{ const sc=tc.status==='PASS'?'#10b981':tc.status==='FAIL'?'#ef4444':'#f59e0b'; const si=tc.status==='PASS'?'✅':tc.status==='FAIL'?'❌':'⏭'; return(<tr key={i} style={{ borderBottom:'1px solid #1c1f2e' }}><td style={{ padding:'9px 12px', color:'#e1e4e8', fontFamily:'monospace', fontSize:12 }}>{tc.name}</td><td style={{ padding:'9px 12px' }}><span style={{ background:'#6366f120', color:'#818cf8', borderRadius:4, padding:'1px 6px', fontSize:10 }}>{tc.type}</span></td><td style={{ padding:'9px 12px', color:'#6b7280', fontSize:11 }}>{tc.duration}</td><td style={{ padding:'9px 12px' }}><span style={{ background:sc+'20', color:sc, borderRadius:4, padding:'2px 8px', fontSize:11, fontWeight:600 }}>{si} {tc.status}</span></td></tr>) })}</tbody>
          </table>
        </div>
      )}
      <div style={{ background:score>=70?'#10b98115':'#ef444415', borderRadius:10, padding:16, border:`1px solid ${score>=70?'#10b981':'#ef4444'}40`, display:'flex', alignItems:'center', gap:12 }}>
        <span style={{ fontSize:28 }}>{score>=80?'🟢':score>=60?'🟡':'🔴'}</span>
        <div>
          <div style={{ color:score>=80?'#10b981':score>=60?'#f59e0b':'#ef4444', fontWeight:700, fontSize:14 }}>{isVi?(score>=80?'Code đạt chất lượng tốt':score>=60?'Code cần cải thiện':'Code có nhiều vấn đề nghiêm trọng'):(score>=80?'Code quality is good':score>=60?'Code needs improvement':'Code has critical issues')}</div>
          <div style={{ color:'#6b7280', fontSize:12, marginTop:2 }}>{isVi?`Tìm thấy ${issues.length} vấn đề • ${passed}/${total} test đạt • Điểm: ${score}/100`:`Found ${issues.length} issues • ${passed}/${total} tests passed • Score: ${score}/100`}</div>
        </div>
      </div>
    </div>
  )
}
